spring.application.name=Mobile

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/MobileDB?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=dreamer
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

spring.devtools.restart.enabled=true


# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Naming Strategy (Optional)
spring.jpa.properties.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable detailed logging for SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
#logging.level.root=DEBUG
#logging.level.org.springframework.boot=INFO
logging.level.org.hibernate.type.descriptor.sql=trace

offers.api.baseUrl=${OFFERS_BASE_URL:http://localhost:8080}

jwt.secret=${JWT_KEY:WSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8IWSdv1kEE1tCT1a8ihRSqfwMNzlPBq8I}
jwt.expiration=${JWT_EXPIRATION:60000}

