INSERT INTO brands (brand_name) VALUES ('Acura');
INSERT INTO brands (brand_name) VALUES ('Alfa Romeo');
INSERT INTO brands (brand_name) VALUES ('Aston Martin');
INSERT INTO brands (brand_name) VALUES ('Audi');
INSERT INTO brands (brand_name) VALUES ('Bentley');
INSERT INTO brands (brand_name) VALUES ('BMW');
INSERT INTO brands (brand_name) VALUES ('Bugatti');
INSERT INTO brands (brand_name) VALUES ('Cadillac');
INSERT INTO brands (brand_name) VALUES ('Chevrolet');
INSERT INTO brands (brand_name) VALUES ('Chrysler');
INSERT INTO brands (brand_name) VALUES ('Citroën');
INSERT INTO brands (brand_name) VALUES ('Dacia');
INSERT INTO brands (brand_name) VALUES ('Dodge');
INSERT INTO brands (brand_name) VALUES ('Ferrari');
INSERT INTO brands (brand_name) VALUES ('Fiat');
INSERT INTO brands (brand_name) VALUES ('Ford');
INSERT INTO brands (brand_name) VALUES ('Honda');
INSERT INTO brands (brand_name) VALUES ('Hummer');
INSERT INTO brands (brand_name) VALUES ('Hyundai');
INSERT INTO brands (brand_name) VALUES ('Infiniti');
INSERT INTO brands (brand_name) VALUES ('Iveco');
INSERT INTO brands (brand_name) VALUES ('Jaguar');
INSERT INTO brands (brand_name) VALUES ('Jeep');
INSERT INTO brands (brand_name) VALUES ('Kia');
INSERT INTO brands (brand_name) VALUES ('KTM');
INSERT INTO brands (brand_name) VALUES ('Lada');
INSERT INTO brands (brand_name) VALUES ('Lamborghini');
INSERT INTO brands (brand_name) VALUES ('Lancia');
INSERT INTO brands (brand_name) VALUES ('Land Rover');
INSERT INTO brands (brand_name) VALUES ('Lexus');
INSERT INTO brands (brand_name) VALUES ('Lotus');
INSERT INTO brands (brand_name) VALUES ('Maserati');
INSERT INTO brands (brand_name) VALUES ('Mazda');
INSERT INTO brands (brand_name) VALUES ('McLaren');
INSERT INTO brands (brand_name) VALUES ('Mercedes-Benz');
INSERT INTO brands (brand_name) VALUES ('Mini');
INSERT INTO brands (brand_name) VALUES ('Mitsubishi');
INSERT INTO brands (brand_name) VALUES ('Nissan');
INSERT INTO brands (brand_name) VALUES ('Opel');
INSERT INTO brands (brand_name) VALUES ('Peugeot');
INSERT INTO brands (brand_name) VALUES ('Porsche');
INSERT INTO brands (brand_name) VALUES ('Renault');
INSERT INTO brands (brand_name) VALUES ('Rolls-Royce');
INSERT INTO brands (brand_name) VALUES ('Seat');
INSERT INTO brands (brand_name) VALUES ('Skoda');
INSERT INTO brands (brand_name) VALUES ('Smart');
INSERT INTO brands (brand_name) VALUES ('Subaru');
INSERT INTO brands (brand_name) VALUES ('Suzuki');
INSERT INTO brands (brand_name) VALUES ('Tesla');
INSERT INTO brands (brand_name) VALUES ('Toyota');
INSERT INTO brands (brand_name) VALUES ('Volkswagen');
INSERT INTO brands (brand_name) VALUES ('Volvo');



